/**
 * CULINA — Provider registry: the machine-readable API verification matrix
 * (PRD §22, §23, §70).
 *
 * Every provider from the public-apis Food & Drink inventory was inspected and
 * live-verified on 2026-09-02 (HTTPS, response shape, CORS headers, auth needs,
 * availability). Full methodology & raw findings: docs/API-VERIFICATION.md.
 *
 * Classifications:
 *   DIRECT            — browser-ready, no credentials
 *   PROXY_REQUIRED    — usable only through a server-side gateway (CORS-blocked)
 *   API_KEY_REQUIRED  — needs a key; enabling it would require a secret-holding proxy
 *   OAUTH_REQUIRED    — OAuth flow; out of scope for a local-first static app
 *   UNAVAILABLE       — endpoint verified as offline
 *   DISABLED          — reachable but not suitable for this product (documented reason)
 *
 * No secrets are stored here or anywhere in the browser bundle (PRD §72).
 */

export const providers = [
  /* ------------------------------------------------------------------ *
   * ENABLED — verified, browser-compatible foundation integrations
   * ------------------------------------------------------------------ */
  {
    id: 'mealdb',
    name: 'TheMealDB',
    adapter: 'mealdb',
    categories: ['recipes', 'ingredients'],
    entities: ['recipe', 'ingredient'],
    classification: 'DIRECT',
    auth: 'none (free community test key is documented by the provider)',
    baseUrl: 'https://www.themealdb.com/api/json/v1/1',
    https: true,
    cors: true,
    browserCompatible: true,
    enabled: true,
    initialStatus: 'operational',
    rateLimit: 'No published limit; community endpoint — cached & debounced by CULINA',
    attribution: 'Recipe data courtesy of TheMealDB.com',
    attributionUrl: 'https://www.themealdb.com',
    docsUrl: 'https://www.themealdb.com/api.php',
    license: 'Free for evaluation with attribution; production keys support the project',
    testEndpoint: '/random.php',
    verifiedAt: '2026-09-02',
    verifiedHow: 'Live probe: 200 JSON, Access-Control-Allow-Origin: *',
    notes: 'Provides meals, categories, areas/cuisines, ingredient lists & filtering. No cooking times, servings or nutrition — those fields stay null, never fabricated.',
  },
  {
    id: 'cocktaildb',
    name: 'TheCocktailDB',
    adapter: 'cocktaildb',
    categories: ['drinks', 'cocktails'],
    entities: ['drink'],
    classification: 'DIRECT',
    auth: 'none (free community test key is documented by the provider)',
    baseUrl: 'https://www.thecocktaildb.com/api/json/v1/1',
    https: true,
    cors: true,
    browserCompatible: true,
    enabled: true,
    initialStatus: 'operational',
    rateLimit: 'No published limit; community endpoint — cached & debounced by CULINA',
    attribution: 'Cocktail data courtesy of TheCocktailDB.com',
    attributionUrl: 'https://www.thecocktaildb.com',
    docsUrl: 'https://www.thecocktaildb.com/api.php',
    license: 'Free for evaluation with attribution; production keys support the project',
    testEndpoint: '/random.php',
    verifiedAt: '2026-09-02',
    verifiedHow: 'Live probe: 200 JSON, Access-Control-Allow-Origin: *',
    notes: 'Cocktails with ingredients, measures, glassware and IBA categories.',
  },
  {
    id: 'fruityvice',
    name: 'Fruityvice',
    adapter: 'fruityvice',
    categories: ['ingredients', 'fruits', 'nutrition'],
    entities: ['fruit'],
    classification: 'PROXY_REQUIRED',
    proxyPath: '/api/fruityvice',
    auth: 'none',
    baseUrl: 'https://www.fruityvice.com',
    https: true,
    cors: false,
    browserCompatible: false, // direct browser calls blocked; works via CULINA gateway
    enabled: true,
    initialStatus: 'operational',
    rateLimit: 'No published limit',
    attribution: 'Fruit data courtesy of Fruityvice',
    attributionUrl: 'https://www.fruityvice.com',
    docsUrl: 'https://www.fruityvice.com/api',
    license: 'Free open API',
    testEndpoint: '/api/fruit/1',
    verifiedAt: '2026-09-02',
    verifiedHow: 'Live probe: 200 JSON but NO Access-Control-Allow-Origin header → browser-blocked; verified working through the CULINA gateway proxy',
    notes: 'Botanical data (family, genus, order) and per-100 g nutrition for fruits. Reached through the same-origin gateway (server.js / vite proxy) per PRD §72. On a host without the gateway it reports “configuration required”.',
  },
  {
    id: 'foodish',
    name: 'Foodish',
    adapter: 'foodish',
    categories: ['images'],
    entities: ['image'],
    classification: 'DIRECT',
    auth: 'none',
    baseUrl: 'https://foodish-api.com',
    https: true,
    cors: true,
    browserCompatible: true,
    enabled: true,
    initialStatus: 'operational',
    rateLimit: 'No published limit',
    attribution: 'Food photography via Foodish',
    attributionUrl: 'https://github.com/surhud004/Foodish',
    docsUrl: 'https://github.com/surhud004/Foodish#readme',
    license: 'Open source (GitHub)',
    testEndpoint: '/api/',
    verifiedAt: '2026-09-02',
    verifiedHow: 'Live probe: 200 JSON, Access-Control-Allow-Origin: *',
    notes: 'Random food photography. The provider removed category endpoints (404 on /api/{category}), so CULINA uses the random endpoint only.',
  },
  {
    id: 'openbrewerydb',
    name: 'Open Brewery DB',
    adapter: 'openbrewerydb',
    categories: ['drinks', 'breweries'],
    entities: ['brewery'],
    classification: 'DIRECT',
    auth: 'none',
    baseUrl: 'https://api.openbrewerydb.org/v1',
    https: true,
    cors: true,
    browserCompatible: true,
    enabled: true,
    initialStatus: 'operational',
    rateLimit: '120 requests per rate-limit window per IP (observed via x-ratelimit headers)',
    attribution: 'Brewery data courtesy of Open Brewery DB',
    attributionUrl: 'https://www.openbrewerydb.org',
    docsUrl: 'https://www.openbrewerydb.org/docs',
    license: 'Open data project — see documentation for current terms',
    testEndpoint: '/breweries?per_page=1',
    verifiedAt: '2026-09-02',
    verifiedHow: 'Live probe: 200 JSON, permissive CORS (origin echo + credentials)',
    notes: '11,800+ breweries with types, addresses, coordinates and websites. CULINA caches list results for 10 minutes and search results for 5 to respect the rate limit.',
  },
  {
    id: 'openfoodfacts',
    name: 'Open Food Facts',
    adapter: 'openfoodfacts',
    categories: ['products', 'nutrition'],
    entities: ['product'],
    classification: 'DIRECT',
    auth: 'none',
    baseUrl: 'https://world.openfoodfacts.org',
    https: true,
    cors: true,
    browserCompatible: true,
    enabled: true,
    initialStatus: 'degraded',
    rateLimit: 'Fair use; search endpoints intermittently enter maintenance mode (HTTP 503) under load',
    attribution: 'Data from Open Food Facts — ODbL',
    attributionUrl: 'https://world.openfoodfacts.org',
    docsUrl: 'https://openfoodfacts.github.io/openfoodfacts-server/api/',
    license: 'Open Database License (ODbL) 1.0 — attribution required',
    testEndpoint: '/api/v2/product/3017620422003.json?fields=product_name',
    verifiedAt: '2026-09-02',
    verifiedHow: 'Live probe: product endpoint 200 JSON with CORS *; text-search endpoints returned 503 maintenance pages under load (retries + honest degraded state implemented)',
    notes: '2.9M+ food products with ingredients, Nutri-Score, NOVA and per-100 g nutriments. Barcode lookup is reliable; text search is retried with backoff and can report partial unavailability.',
  },
  {
    id: 'sampleapis-coffee',
    name: 'SampleAPIs — Coffee',
    adapter: 'coffee',
    categories: ['drinks', 'coffee'],
    entities: ['coffee'],
    classification: 'DIRECT',
    auth: 'none',
    baseUrl: 'https://api.sampleapis.com/coffee',
    https: true,
    cors: true,
    browserCompatible: true,
    enabled: true,
    initialStatus: 'operational',
    rateLimit: 'No published limit (community service)',
    attribution: 'Coffee guides via SampleAPIs (community dataset)',
    attributionUrl: 'https://sampleapis.com',
    docsUrl: 'https://sampleapis.com/api-list/coffee',
    license: 'Free community demo dataset — no SLA',
    testEndpoint: '/hot',
    verifiedAt: '2026-09-02',
    verifiedHow: 'Live probe: 200 JSON, Access-Control-Allow-Origin: *',
    notes: 'Hot & iced coffee guides with ingredients and photography. Labeled throughout as a community dataset.',
  },
  {
    id: 'sampleapis-beers',
    name: 'SampleAPIs — Beers',
    adapter: 'beers',
    categories: ['drinks', 'beer'],
    entities: ['beer'],
    classification: 'DIRECT',
    auth: 'none',
    baseUrl: 'https://api.sampleapis.com/beers',
    https: true,
    cors: true,
    browserCompatible: true,
    enabled: true,
    initialStatus: 'operational',
    rateLimit: 'No published limit (community service)',
    attribution: 'Beer listings via SampleAPIs (community dataset)',
    attributionUrl: 'https://sampleapis.com',
    docsUrl: 'https://sampleapis.com/api-list/beers',
    license: 'Free community demo dataset — no SLA',
    testEndpoint: '/ale',
    verifiedAt: '2026-09-02',
    verifiedHow: 'Live probe: 200 JSON, Access-Control-Allow-Origin: * (ale & stouts endpoints)',
    notes: 'Ale and stout listings with price & community ratings. ABV/brewery/description are not provided by this source and are never fabricated. Supersedes PunkAPI, which is offline.',
  },

  /* ------------------------------------------------------------------ *
   * VERIFIED OFFLINE — classified UNAVAILABLE
   * ------------------------------------------------------------------ */
  {
    id: 'punkapi',
    name: 'PunkAPI (BrewDog)',
    adapter: null,
    categories: ['drinks', 'beer'],
    entities: ['beer'],
    classification: 'UNAVAILABLE',
    auth: 'none',
    baseUrl: 'https://api.punkapi.com/v2',
    https: true,
    cors: null,
    browserCompatible: false,
    enabled: false,
    initialStatus: 'unavailable',
    attribution: '—',
    docsUrl: 'https://punkapi.com',
    verifiedAt: '2026-09-02',
    verifiedHow: 'DNS lookup fails (NXDOMAIN for api.punkapi.com / punkapi.com) — the service has been sunset',
    notes: 'The classic BrewDog beer API is offline. Beer discovery falls back to SampleAPIs — Beers (compatible data) per the fallback policy (PRD §38).',
  },
  {
    id: 'lcbo',
    name: 'LCBO',
    adapter: null,
    categories: ['drinks'],
    entities: [],
    classification: 'UNAVAILABLE',
    auth: 'apiKey',
    baseUrl: 'https://lcboapi.com',
    https: true,
    cors: null,
    browserCompatible: false,
    enabled: false,
    initialStatus: 'unavailable',
    attribution: '—',
    docsUrl: 'https://lcboapi.com',
    verifiedAt: '2026-09-02',
    verifiedHow: 'DNS lookup fails (NXDOMAIN for lcboapi.com)',
    notes: 'Canadian alcohol catalog API — offline.',
  },
  {
    id: 'rustybeer',
    name: 'Rustybeer',
    adapter: null,
    categories: ['drinks', 'beer'],
    entities: [],
    classification: 'UNAVAILABLE',
    auth: 'none',
    baseUrl: 'https://rustybeer.herokuapp.com',
    https: true,
    cors: false,
    browserCompatible: false,
    enabled: false,
    initialStatus: 'unavailable',
    attribution: '—',
    docsUrl: 'https://github.com/krishh-sedha/rustybeer',
    verifiedAt: '2026-09-02',
    verifiedHow: 'Hosted on free Heroku dynos; the public inventory lists CORS “No” — free-tier Heroku apps have been retired',
    notes: 'Beer brewing calculator API — offline.',
  },

  /* ------------------------------------------------------------------ *
   * CREDENTIAL-GATED — would require a secret-holding proxy (PRD §72)
   * ------------------------------------------------------------------ */
  {
    id: 'edamam-nutrition',
    name: 'Edamam Nutrition',
    adapter: null,
    categories: ['nutrition'],
    entities: [],
    classification: 'API_KEY_REQUIRED',
    auth: 'apiKey (application id + key)',
    baseUrl: 'https://api.edamam.com',
    https: true,
    cors: null,
    browserCompatible: false,
    enabled: false,
    initialStatus: 'config-required',
    attribution: '—',
    docsUrl: 'https://developer.edamam.com/edamam-docs-nutrition-api',
    verifiedAt: '2026-09-02',
    verifiedHow: 'Provider documentation requires an application ID + key; embedding those in a browser bundle would expose them publicly',
    notes: 'Natural-language nutrition analysis. Enabling it would require the gateway pattern with server-held credentials.',
  },
  {
    id: 'edamam-recipes',
    name: 'Edamam Recipes',
    adapter: null,
    categories: ['recipes'],
    entities: [],
    classification: 'API_KEY_REQUIRED',
    auth: 'apiKey (application id + key)',
    baseUrl: 'https://api.edamam.com',
    https: true,
    cors: null,
    browserCompatible: false,
    enabled: false,
    initialStatus: 'config-required',
    attribution: '—',
    docsUrl: 'https://developer.edamam.com/edamam-docs-recipe-api',
    verifiedAt: '2026-09-02',
    verifiedHow: 'Provider documentation requires credentials',
    notes: 'Recipe search with diet/health filters. Would require the gateway pattern.',
  },
  {
    id: 'spoonacular',
    name: 'Spoonacular',
    adapter: null,
    categories: ['recipes', 'products', 'nutrition'],
    entities: [],
    classification: 'API_KEY_REQUIRED',
    auth: 'apiKey',
    baseUrl: 'https://api.spoonacular.com',
    https: true,
    cors: null,
    browserCompatible: false,
    enabled: false,
    initialStatus: 'config-required',
    attribution: '—',
    docsUrl: 'https://spoonacular.com/food-api',
    verifiedAt: '2026-09-02',
    verifiedHow: 'Provider documentation requires a key with quota-based pricing',
    notes: 'Comprehensive food API. Key would have to be held by a proxy; free tier is limited.',
  },
  {
    id: 'tasty',
    name: 'Tasty (via RapidAPI)',
    adapter: null,
    categories: ['recipes'],
    entities: [],
    classification: 'API_KEY_REQUIRED',
    auth: 'apiKey (RapidAPI)',
    baseUrl: 'https://tasty.p.rapidapi.com',
    https: true,
    cors: null,
    browserCompatible: false,
    enabled: false,
    initialStatus: 'config-required',
    attribution: '—',
    docsUrl: 'https://rapidapi.com/apidojo/api/tasty/',
    verifiedAt: '2026-09-02',
    verifiedHow: 'Distributed through RapidAPI, which requires a key with usage-based limits',
    notes: 'Recipe & plan data from the Tasty network.',
  },
  {
    id: 'recipeapi',
    name: 'RecipeAPI',
    adapter: null,
    categories: ['recipes'],
    entities: [],
    classification: 'API_KEY_REQUIRED',
    auth: 'apiKey',
    baseUrl: 'https://recipeapi.io',
    https: true,
    cors: true,
    browserCompatible: false,
    enabled: false,
    initialStatus: 'config-required',
    attribution: '—',
    docsUrl: 'https://recipeapi.io',
    verifiedAt: '2026-09-02',
    verifiedHow: 'Provider documentation requires a key (public inventory lists CORS “Yes”)',
    notes: 'Would be a candidate DIRECT-style integration once credentials are provided through a gateway.',
  },
  {
    id: 'zestful',
    name: 'Zestful',
    adapter: null,
    categories: ['ingredients'],
    entities: [],
    classification: 'API_KEY_REQUIRED',
    auth: 'apiKey',
    baseUrl: 'https://api.zestfuldata.com',
    https: true,
    cors: true,
    browserCompatible: false,
    enabled: false,
    initialStatus: 'config-required',
    attribution: '—',
    docsUrl: 'https://zestfuldata.com/',
    verifiedAt: '2026-09-02',
    verifiedHow: 'Provider documentation requires a key',
    notes: 'Recipe-ingredient parsing (quantities, units). Interesting for shopping-list normalization.',
  },
  {
    id: 'chomp',
    name: 'Chomp',
    adapter: null,
    categories: ['products'],
    entities: [],
    classification: 'API_KEY_REQUIRED',
    auth: 'apiKey',
    baseUrl: 'https://chompthis.com/api',
    https: true,
    cors: null,
    browserCompatible: false,
    enabled: false,
    initialStatus: 'config-required',
    attribution: '—',
    docsUrl: 'https://chompthis.com/api/',
    verifiedAt: '2026-09-02',
    verifiedHow: 'Provider documentation requires a key',
    notes: 'Grocery product data.',
  },
  {
    id: 'food-info',
    name: 'Food Info',
    adapter: null,
    categories: ['nutrition'],
    entities: [],
    classification: 'API_KEY_REQUIRED',
    auth: 'apiKey',
    baseUrl: 'https://food-info.org',
    https: true,
    cors: false,
    browserCompatible: false,
    enabled: false,
    initialStatus: 'config-required',
    attribution: '—',
    docsUrl: 'https://food-info.org/developer',
    verifiedAt: '2026-09-02',
    verifiedHow: 'Public inventory lists auth “apiKey”, CORS “No” — double barrier for browser use',
    notes: 'Nutrition from six national food-composition datasets.',
  },
  {
    id: 'kroger',
    name: 'Kroger',
    adapter: null,
    categories: ['products'],
    entities: [],
    classification: 'OAUTH_REQUIRED',
    auth: 'OAuth 2.0 (client credentials)',
    baseUrl: 'https://api.kroger.com',
    https: true,
    cors: null,
    browserCompatible: false,
    enabled: false,
    initialStatus: 'config-required',
    attribution: '—',
    docsUrl: 'https://developer.kroger.com/reference',
    verifiedAt: '2026-09-02',
    verifiedHow: 'OAuth 2.0 flow with client credentials — client secrets must never live in a browser (PRD §47/§72)',
    notes: 'Supermarket product & pricing data.',
  },
  {
    id: 'untappd',
    name: 'Untappd',
    adapter: null,
    categories: ['drinks', 'beer'],
    entities: [],
    classification: 'OAUTH_REQUIRED',
    auth: 'OAuth',
    baseUrl: 'https://api.untappd.com/v4',
    https: true,
    cors: null,
    browserCompatible: false,
    enabled: false,
    initialStatus: 'config-required',
    attribution: '—',
    docsUrl: 'https://untappd.com/api/docs',
    verifiedAt: '2026-09-02',
    verifiedHow: 'OAuth-based API; not suited to a keyless static frontend',
    notes: 'Social beer check-ins & ratings.',
  },
  {
    id: 'systembolaget',
    name: 'Systembolaget',
    adapter: null,
    categories: ['drinks'],
    entities: [],
    classification: 'API_KEY_REQUIRED',
    auth: 'apiKey',
    baseUrl: 'https://api-portal.systembolaget.se',
    https: true,
    cors: null,
    browserCompatible: false,
    enabled: false,
    initialStatus: 'config-required',
    attribution: '—',
    docsUrl: 'https://api-portal.systembolaget.se',
    verifiedAt: '2026-09-02',
    verifiedHow: 'Provider portal requires an API key',
    notes: 'Swedish alcohol retailer catalog.',
  },
  {
    id: 'whats-on-the-menu',
    name: 'What’s on the menu? (NYPL)',
    adapter: null,
    categories: ['historical'],
    entities: [],
    classification: 'UNAVAILABLE',
    auth: 'apiKey',
    baseUrl: 'http://nypl.github.io/menus-api',
    https: false,
    cors: null,
    browserCompatible: false,
    enabled: false,
    initialStatus: 'unavailable',
    attribution: '—',
    docsUrl: 'http://nypl.github.io/menus-api/',
    verifiedAt: '2026-09-02',
    verifiedHow: 'HTTP-only endpoint (no TLS) — mixed content is blocked by browsers',
    notes: 'Historical restaurant menus from NYPL.',
  },

  /* ------------------------------------------------------------------ *
   * VERIFIED REACHABLE BUT OUT OF SCOPE / UNSUITABLE — DISABLED
   * ------------------------------------------------------------------ */
  {
    id: 'baconmockup',
    name: 'BaconMockup',
    adapter: null,
    categories: ['images'],
    entities: [],
    classification: 'DISABLED',
    auth: 'none',
    baseUrl: 'https://baconmockup.com',
    https: true,
    cors: true,
    browserCompatible: true,
    enabled: false,
    initialStatus: 'disabled',
    attribution: '—',
    docsUrl: 'https://baconmockup.com/',
    verifiedAt: '2026-09-02',
    verifiedHow: 'Live probe: responds (301 → images) — reachable but unsuitable',
    notes: 'Novelty placeholder imagery (resizable bacon photos). CULINA does not use placeholder-quality visuals; disabled by product decision.',
  },
  {
    id: 'coffee-alexflipnote',
    name: 'Coffee (alexflipnote)',
    adapter: null,
    categories: ['images', 'drinks'],
    entities: [],
    classification: 'DISABLED',
    auth: 'none',
    baseUrl: 'https://coffee.alexflipnote.dev',
    https: true,
    cors: false,
    browserCompatible: false,
    enabled: false,
    initialStatus: 'disabled',
    attribution: '—',
    docsUrl: 'https://coffee.alexflipnote.dev/',
    verifiedAt: '2026-09-02',
    verifiedHow: 'Live probe: 200 JSON but no Access-Control-Allow-Origin header → browser-blocked; superseded by SampleAPIs Coffee (which includes recipes)',
    notes: 'Random coffee photography only.',
  },
  {
    id: 'whiskyhunter',
    name: 'WhiskyHunter',
    adapter: null,
    categories: ['drinks'],
    entities: [],
    classification: 'DISABLED',
    auth: 'none',
    baseUrl: 'https://whiskyhunter.net/api',
    https: true,
    cors: null,
    browserCompatible: null,
    enabled: false,
    initialStatus: 'disabled',
    attribution: '—',
    docsUrl: 'https://whiskyhunter.net/api/',
    verifiedAt: '2026-09-02',
    verifiedHow: 'Host resolves; API responds with redirects — reachable but out of product scope',
    notes: 'Whisky auction statistics. Not food/drink discovery; disabled by product decision.',
  },
  {
    id: 'report-of-the-week',
    name: 'The Report of the Week',
    adapter: null,
    categories: ['reviews'],
    entities: [],
    classification: 'DISABLED',
    auth: 'none',
    baseUrl: 'https://trtw.joysticklabs.io',
    https: true,
    cors: null,
    browserCompatible: null,
    enabled: false,
    initialStatus: 'disabled',
    attribution: '—',
    docsUrl: 'https://github.com/andyklimczak/TheReportOfTheWeek-API',
    verifiedAt: '2026-09-02',
    verifiedHow: 'Community fan API for video reviews — out of product scope',
    notes: 'Food & drink video reviews; no structured nutrition/recipe data.',
  },
  {
    id: 'tacofancy',
    name: 'TacoFancy',
    adapter: null,
    categories: ['recipes'],
    entities: [],
    classification: 'UNAVAILABLE',
    auth: 'none',
    baseUrl: 'http://taco-randomizer.herokuapp.com',
    https: false,
    cors: null,
    browserCompatible: false,
    enabled: false,
    initialStatus: 'unavailable',
    attribution: '—',
    docsUrl: 'https://github.com/evz/tacofancy-api',
    verifiedAt: '2026-09-02',
    verifiedHow: 'Public inventory lists HTTPS “No” — mixed content is blocked by modern browsers',
    notes: 'Community taco recipe database.',
  },
];

const byId = new Map(providers.map((p) => [p.id, p]));

export function getProvider(id) {
  return byId.get(id) || null;
}

export function enabledProviders() {
  return providers.filter((p) => p.enabled);
}

export function providerLabel(id) {
  return byId.get(id)?.name || id;
}

export const CLASSIFICATION_LABELS = {
  DIRECT: 'Direct — browser-ready',
  PROXY_REQUIRED: 'Proxy required',
  API_KEY_REQUIRED: 'API key required',
  OAUTH_REQUIRED: 'OAuth required',
  UNAVAILABLE: 'Offline',
  DISABLED: 'Disabled',
};

export const STATUS_LABELS = {
  operational: 'Operational',
  degraded: 'Degraded',
  unavailable: 'Unavailable',
  'config-required': 'Configuration required',
  'browser-restricted': 'Browser restricted',
  disabled: 'Disabled',
};
